#!/bin/sh
# elvis: docs.rs
# gabi_250@live.com 20200411
#
# Based on the duckduckgo elvi
. surfraw || exit 1

w3_config_hook () {
    def     SURFRAW_docsrs_results             "$SURFRAW_results"
    def     SURFRAW_docsrs_base_url            "docs.rs"
    def     SURFRAW_docsrs_search              search
    def     SURFRAW_docsrs_params              "&kg=g"
    defyn   SURFRAW_docsrs_exact_match         0
    defyn   SURFRAW_docsrs_https_arg           0
}

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Surfraw search the web using docs.rs
Local options:
    -s,-insecure                disable SSL search
    -e,-exact                   disable SSL search
EOF
    w3_global_usage
}

w3_parse_option_hook () {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -s|-sec*)           setoptyn    SURFRAW_docsrs_https_arg           1 ;;
    -e|-exact*)         setoptyn    SURFRAW_docsrs_exact_match         1 ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

if [ "${SURFRAW_docsrs_https_arg}" = 0 ] ; then
    SURFRAW_docsrs_base_url="https://${SURFRAW_docsrs_base_url}"
else
    SURFRAW_docsrs_base_url="http://${SURFRAW_docsrs_base_url}"
fi

if [ "$SURFRAW_graphical" != "yes" ] ; then
    SURFRAW_docsrs_params="${SURFRAW_docsrs_params}&kf=-1&kz=-1&kq=-1&kv=-1"
fi

escaped_args=`w3_url_of_arg $w3_args`

if [ "$SURFRAW_docsrs_exact_match" = 1 ]; then
    w3_browse_url "${SURFRAW_docsrs_base_url}/${escaped_args}${SURFRAW_docsrs_params}"
else
    w3_browse_url "${SURFRAW_docsrs_base_url}/releases/search?query=${escaped_args}${SURFRAW_docsrs_params}"
fi

